### ISSUE TITLE
What is the data structure of output_batch ?

### ISSUE THREAD

**Issue by zhouzhouqian** [yiyang7/cs231n_proj#1]
I want to save the result image. .So, what is the data structure of output_batch ? I don't know how to writte the code ? can you writte it ?

**Comment by yiyang7** [comment]
see line 81-88 in evaluate_cnn.py

**Comment by alohaleonardo** [comment]
> I want to save the result image. .So, what is the data structure of output_batch ? I don't know how to writte the code ? can you writte it ?

see line 81-88 in evaluate_cnn.py
