### ISSUE TITLE
TVLoss question.

### ISSUE THREAD

**Issue by mtroym** [yiyang7/cs231n_proj#2]
I found tv loss formula in wiki:
![](http://www.sciweavers.org/upload/Tex2Img_1547803162/render.png)
while your code shows you did not have a sqrt operation.
could you tell me why?

**Comment by yongduek** [comment]
The two are basically the same. Well you may say they are different and actually they are. However, regarding the objective that you want to obtain, minimizing either will eventually give you the same result.

**Comment by mtroym** [comment]
Thanks.
